### ISSUE TITLE
Por favor modifica page login y sign up

### ISSUE THREAD

**Issue by AdanSerrano** [OrganizationAdan/PageProyectFinal#19]
**Describe the bug**

**To Reproduce**
3. Scroll down to '....'and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by Yyauw** [comment]
Se termino de agregar responsive a dispositivos tablet, pendiente pull request page-modify-yauw ==> Main
